sonar.projectKey=levelup-english-v3-react
sonar.sources=frontend/src, backend, admin-panel/src
sonar.exclusions=backend/database/seed.sql, backend/database/schema.sql, backend/scratch/**, **/*.json, **/*.css, **/*.html, **/vite.config.js, **/eslint.config.js, **/config.js
sonar.cpd.exclusions=admin-panel/src/api/**, admin-panel/src/pages/Login.jsx, admin-panel/src/context/AuthContext.jsx, frontend/src/api/**, frontend/src/context/AuthContext.jsx, frontend/src/pages/Login.jsx, backend/database/**
