sonar.projectKey=levelup-english-v3-react
sonar.sources=frontend/src, backend, admin-panel/src
sonar.cpd.exclusions=admin-panel/src/api/**, admin-panel/src/pages/Login.jsx, admin-panel/src/context/AuthContext.jsx, **/*.css, **/*.html, **/vite.config.js
