const fs = require('fs');

const vocabFile = 'src/data/vocabulary.js';
let content = fs.readFileSync(vocabFile, 'utf8');

const regularVerbsNew = [
    { en: 'Accept', es: 'Aceptar', past: 'Accepted', part: 'Accepted' },
    { en: 'Add', es: 'Añadir / Sumar', past: 'Added', part: 'Added' },
    { en: 'Admire', es: 'Admirar', past: 'Admired', part: 'Admired' },
    { en: 'Admit', es: 'Admitir', past: 'Admitted', part: 'Admitted' },
    { en: 'Advise', es: 'Aconsejar', past: 'Advised', part: 'Advised' },
    { en: 'Agree', es: 'Acordar / Estar de acuerdo', past: 'Agreed', part: 'Agreed' },
    { en: 'Allow', es: 'Permitir', past: 'Allowed', part: 'Allowed' },
    { en: 'Announce', es: 'Anunciar', past: 'Announced', part: 'Announced' },
    { en: 'Answer', es: 'Responder', past: 'Answered', part: 'Answered' },
    { en: 'Apologize', es: 'Disculparse', past: 'Apologized', part: 'Apologized' },
    { en: 'Appear', es: 'Aparecer', past: 'Appeared', part: 'Appeared' },
    { en: 'Appreciate', es: 'Apreciar', past: 'Appreciated', part: 'Appreciated' },
    { en: 'Approve', es: 'Aprobar', past: 'Approved', part: 'Approved' },
    { en: 'Argue', es: 'Discutir / Argumentar', past: 'Argued', part: 'Argued' },
    { en: 'Arrive', es: 'Llegar', past: 'Arrived', part: 'Arrived' },
    { en: 'Ask', es: 'Preguntar / Pedir', past: 'Asked', part: 'Asked' },
    { en: 'Assume', es: 'Asumir', past: 'Assumed', part: 'Assumed' },
    { en: 'Attach', es: 'Adjuntar', past: 'Attached', part: 'Attached' },
    { en: 'Attack', es: 'Atacar', past: 'Attacked', part: 'Attacked' },
    { en: 'Attempt', es: 'Intentar', past: 'Attempted', part: 'Attempted' },
    { en: 'Attend', es: 'Asistir', past: 'Attended', part: 'Attended' },
    { en: 'Attract', es: 'Atraer', past: 'Attracted', part: 'Attracted' },
    { en: 'Avoid', es: 'Evitar', past: 'Avoided', part: 'Avoided' },
    { en: 'Bake', es: 'Hornear', past: 'Baked', part: 'Baked' },
    { en: 'Behave', es: 'Comportarse', past: 'Behaved', part: 'Behaved' },
    { en: 'Belong', es: 'Pertenecer', past: 'Belonged', part: 'Belonged' },
    { en: 'Boil', es: 'Hervir', past: 'Boiled', part: 'Boiled' },
    { en: 'Borrow', es: 'Pedir prestado', past: 'Borrowed', part: 'Borrowed' },
    { en: 'Bother', es: 'Molestar', past: 'Bothered', part: 'Bothered' },
    { en: 'Call', es: 'Llamar', past: 'Called', part: 'Called' },
    { en: 'Care', es: 'Importar / Cuidar', past: 'Cared', part: 'Cared' },
    { en: 'Carry', es: 'Llevar', past: 'Carried', part: 'Carried' },
    { en: 'Cause', es: 'Causar', past: 'Caused', part: 'Caused' },
    { en: 'Change', es: 'Cambiar', past: 'Changed', part: 'Changed' },
    { en: 'Charge', es: 'Cargar / Cobrar', past: 'Charged', part: 'Charged' },
    { en: 'Chase', es: 'Perseguir', past: 'Chased', part: 'Chased' },
    { en: 'Check', es: 'Comprobar / Revisar', past: 'Checked', part: 'Checked' },
    { en: 'Clean', es: 'Limpiar', past: 'Cleaned', part: 'Cleaned' },
    { en: 'Clear', es: 'Aclarar / Despejar', past: 'Cleared', part: 'Cleared' },
    { en: 'Climb', es: 'Escalar', past: 'Climbed', part: 'Climbed' },
    { en: 'Close', es: 'Cerrar', past: 'Closed', part: 'Closed' },
    { en: 'Compare', es: 'Comparar', past: 'Compared', part: 'Compared' },
    { en: 'Complain', es: 'Quejarse', past: 'Complained', part: 'Complained' },
    { en: 'Complete', es: 'Completar', past: 'Completed', part: 'Completed' },
    { en: 'Consider', es: 'Considerar', past: 'Considered', part: 'Considered' },
    { en: 'Continue', es: 'Continuar', past: 'Continued', part: 'Continued' },
    { en: 'Cook', es: 'Cocinar', past: 'Cooked', part: 'Cooked' },
    { en: 'Copy', es: 'Copiar', past: 'Copied', part: 'Copied' },
    { en: 'Correct', es: 'Corregir', past: 'Corrected', part: 'Corrected' },
    { en: 'Count', es: 'Contar', past: 'Counted', part: 'Counted' },
    { en: 'Cover', es: 'Cubrir', past: 'Covered', part: 'Covered' },
    { en: 'Create', es: 'Crear', past: 'Created', part: 'Created' },
    { en: 'Cross', es: 'Cruzar', past: 'Crossed', part: 'Crossed' },
    { en: 'Cry', es: 'Llorar', past: 'Cried', part: 'Cried' },
    { en: 'Dance', es: 'Bailar', past: 'Danced', part: 'Danced' },
    { en: 'Decide', es: 'Decidir', past: 'Decided', part: 'Decided' },
    { en: 'Deliver', es: 'Entregar', past: 'Delivered', part: 'Delivered' },
    { en: 'Depend', es: 'Depender', past: 'Depended', part: 'Depended' },
    { en: 'Describe', es: 'Describir', past: 'Described', part: 'Described' },
    { en: 'Design', es: 'Diseñar', past: 'Designed', part: 'Designed' },
    { en: 'Destroy', es: 'Destruir', past: 'Destroyed', part: 'Destroyed' },
    { en: 'Develop', es: 'Desarrollar', past: 'Developed', part: 'Developed' },
    { en: 'Discover', es: 'Descubrir', past: 'Discovered', part: 'Discovered' },
    { en: 'Discuss', es: 'Discutir', past: 'Discussed', part: 'Discussed' },
    { en: 'Divide', es: 'Dividir', past: 'Divided', part: 'Divided' },
    { en: 'Dress', es: 'Vestir', past: 'Dressed', part: 'Dressed' },
    { en: 'Drop', es: 'Dejar caer', past: 'Dropped', part: 'Dropped' },
    { en: 'Earn', es: 'Ganar (dinero)', past: 'Earned', part: 'Earned' },
    { en: 'Educate', es: 'Educar', past: 'Educated', part: 'Educated' },
    { en: 'Employ', es: 'Emplear', past: 'Employed', part: 'Employed' },
    { en: 'End', es: 'Terminar', past: 'Ended', part: 'Ended' },
    { en: 'Enjoy', es: 'Disfrutar', past: 'Enjoyed', part: 'Enjoyed' },
    { en: 'Enter', es: 'Entrar', past: 'Entered', part: 'Entered' },
    { en: 'Escape', es: 'Escapar', past: 'Escaped', part: 'Escaped' },
    { en: 'Examine', es: 'Examinar', past: 'Examined', part: 'Examined' },
    { en: 'Exist', es: 'Existir', past: 'Existed', part: 'Existed' },
    { en: 'Expect', es: 'Esperar (expectativa)', past: 'Expected', part: 'Expected' },
    { en: 'Explain', es: 'Explicar', past: 'Explained', part: 'Explained' },
    { en: 'Face', es: 'Enfrentar', past: 'Faced', part: 'Faced' },
    { en: 'Fail', es: 'Fracasar / Suspender', past: 'Failed', part: 'Failed' },
    { en: 'Fill', es: 'Llenar', past: 'Filled', part: 'Filled' },
    { en: 'Finish', es: 'Terminar', past: 'Finished', part: 'Finished' },
    { en: 'Fix', es: 'Arreglar', past: 'Fixed', part: 'Fixed' },
    { en: 'Follow', es: 'Seguir', past: 'Followed', part: 'Followed' },
    { en: 'Guess', es: 'Adivinar', past: 'Guessed', part: 'Guessed' },
    { en: 'Happen', es: 'Suceder', past: 'Happened', part: 'Happened' },
    { en: 'Hate', es: 'Odiar', past: 'Hated', part: 'Hated' },
    { en: 'Help', es: 'Ayudar', past: 'Helped', part: 'Helped' },
    { en: 'Hope', es: 'Esperar (deseo)', past: 'Hoped', part: 'Hoped' },
    { en: 'Identify', es: 'Identificar', past: 'Identified', part: 'Identified' },
    { en: 'Imagine', es: 'Imaginar', past: 'Imagined', part: 'Imagined' },
    { en: 'Improve', es: 'Mejorar', past: 'Improved', part: 'Improved' },
    { en: 'Include', es: 'Incluir', past: 'Included', part: 'Included' },
    { en: 'Increase', es: 'Incrementar', past: 'Increased', part: 'Increased' },
    { en: 'Introduce', es: 'Introducir / Presentar', past: 'Introduced', part: 'Introduced' },
    { en: 'Invite', es: 'Invitar', past: 'Invited', part: 'Invited' },
    { en: 'Join', es: 'Unirse', past: 'Joined', part: 'Joined' },
    { en: 'Jump', es: 'Saltar', past: 'Jumped', part: 'Jumped' },
    { en: 'Kill', es: 'Matar', past: 'Killed', part: 'Killed' },
    { en: 'Love', es: 'Amar', past: 'Loved', part: 'Loved' }
];

const irregularVerbsNew = [
    { en: 'Arise', es: 'Surgir', past: 'Arose', part: 'Arisen' },
    { en: 'Awake', es: 'Despertar', past: 'Awoke', part: 'Awoken' },
    { en: 'Be (am/is/are)', es: 'Ser / Estar', past: 'Was/Were', part: 'Been' },
    { en: 'Bear', es: 'Soportar / Llevar', past: 'Bore', part: 'Borne/Born' },
    { en: 'Beat', es: 'Golpear / Vencer', past: 'Beat', part: 'Beaten' },
    { en: 'Become', es: 'Llegar a ser / Convertirse', past: 'Became', part: 'Become' },
    { en: 'Begin', es: 'Empezar', past: 'Began', part: 'Begun' },
    { en: 'Bend', es: 'Doblar', past: 'Bent', part: 'Bent' },
    { en: 'Bet', es: 'Apostar', past: 'Bet', part: 'Bet' },
    { en: 'Bind', es: 'Atar', past: 'Bound', part: 'Bound' },
    { en: 'Bite', es: 'Morder', past: 'Bit', part: 'Bitten' },
    { en: 'Bleed', es: 'Sangrar', past: 'Bled', part: 'Bled' },
    { en: 'Blow', es: 'Soplar', past: 'Blew', part: 'Blown' },
    { en: 'Break', es: 'Romper', past: 'Broke', part: 'Broken' },
    { en: 'Bring', es: 'Traer', past: 'Brought', part: 'Brought' },
    { en: 'Build', es: 'Construir', past: 'Built', part: 'Built' },
    { en: 'Burn', es: 'Quemar', past: 'Burnt/Burned', part: 'Burnt/Burned' },
    { en: 'Burst', es: 'Estallar', past: 'Burst', part: 'Burst' },
    { en: 'Buy', es: 'Comprar', past: 'Bought', part: 'Bought' },
    { en: 'Cast', es: 'Lanzar / Repartir', past: 'Cast', part: 'Cast' },
    { en: 'Catch', es: 'Atrapar', past: 'Caught', part: 'Caught' },
    { en: 'Choose', es: 'Elegir', past: 'Chose', part: 'Chosen' },
    { en: 'Cling', es: 'Aferrarse', past: 'Clung', part: 'Clung' },
    { en: 'Come', es: 'Venir', past: 'Came', part: 'Come' },
    { en: 'Cost', es: 'Costar', past: 'Cost', part: 'Cost' },
    { en: 'Creep', es: 'Arrastrarse', past: 'Crept', part: 'Crept' },
    { en: 'Cut', es: 'Cortar', past: 'Cut', part: 'Cut' },
    { en: 'Deal', es: 'Tratar / Negociar', past: 'Dealt', part: 'Dealt' },
    { en: 'Dig', es: 'Cavar', past: 'Dug', part: 'Dug' },
    { en: 'Do / Does', es: 'Hacer', past: 'Did', part: 'Done' },
    { en: 'Draw', es: 'Dibujar', past: 'Drew', part: 'Drawn' },
    { en: 'Dream', es: 'Soñar', past: 'Dreamt/Dreamed', part: 'Dreamt/Dreamed' },
    { en: 'Drink', es: 'Beber', past: 'Drank', part: 'Drunk' },
    { en: 'Drive', es: 'Conducir', past: 'Drove', part: 'Driven' },
    { en: 'Eat', es: 'Comer', past: 'Ate', part: 'Eaten' },
    { en: 'Fall', es: 'Caer', past: 'Fell', part: 'Fallen' },
    { en: 'Feed', es: 'Alimentar', past: 'Fed', part: 'Fed' },
    { en: 'Feel', es: 'Sentir', past: 'Felt', part: 'Felt' },
    { en: 'Fight', es: 'Pelear', past: 'Fought', part: 'Fought' },
    { en: 'Find', es: 'Encontrar', past: 'Found', part: 'Found' },
    { en: 'Flee', es: 'Huir', past: 'Fled', part: 'Fled' },
    { en: 'Fling', es: 'Arrojar', past: 'Flung', part: 'Flung' },
    { en: 'Fly', es: 'Volar', past: 'Flew', part: 'Flown' },
    { en: 'Forbid', es: 'Prohibir', past: 'Forbade', part: 'Forbidden' },
    { en: 'Forget', es: 'Olvidar', past: 'Forgot', part: 'Forgotten' },
    { en: 'Forgive', es: 'Perdonar', past: 'Forgave', part: 'Forgiven' },
    { en: 'Freeze', es: 'Congelar', past: 'Froze', part: 'Frozen' },
    { en: 'Get', es: 'Obtener / Conseguir', past: 'Got', part: 'Got/Gotten' },
    { en: 'Give', es: 'Dar', past: 'Gave', part: 'Given' },
    { en: 'Go', es: 'Ir', past: 'Went', part: 'Gone' },
    { en: 'Grind', es: 'Moler', past: 'Ground', part: 'Ground' },
    { en: 'Grow', es: 'Crecer / Cultivar', past: 'Grew', part: 'Grown' },
    { en: 'Hang', es: 'Colgar', past: 'Hung', part: 'Hung' },
    { en: 'Have / Has', es: 'Tener / Haber', past: 'Had', part: 'Had' },
    { en: 'Hear', es: 'Oír', past: 'Heard', part: 'Heard' },
    { en: 'Hide', es: 'Esconder', past: 'Hid', part: 'Hidden' },
    { en: 'Hit', es: 'Golpear', past: 'Hit', part: 'Hit' },
    { en: 'Hold', es: 'Sostener', past: 'Held', part: 'Held' },
    { en: 'Hurt', es: 'Herir / Doler', past: 'Hurt', part: 'Hurt' },
    { en: 'Keep', es: 'Mantener / Guardar', past: 'Kept', part: 'Kept' },
    { en: 'Kneel', es: 'Arrodillarse', past: 'Knelt', part: 'Knelt' },
    { en: 'Know', es: 'Saber / Conocer', past: 'Knew', part: 'Known' },
    { en: 'Lay', es: 'Poner (algo)', past: 'Laid', part: 'Laid' },
    { en: 'Lead', es: 'Liderar / Guiar', past: 'Led', part: 'Led' },
    { en: 'Lean', es: 'Apoyarse', past: 'Leant/Leaned', part: 'Leant/Leaned' },
    { en: 'Leap', es: 'Saltar', past: 'Leapt/Leaped', part: 'Leapt/Leaped' },
    { en: 'Learn', es: 'Aprender', past: 'Learnt/Learned', part: 'Learnt/Learned' },
    { en: 'Leave', es: 'Dejar / Salir', past: 'Left', part: 'Left' },
    { en: 'Lend', es: 'Prestar', past: 'Lent', part: 'Lent' },
    { en: 'Let', es: 'Dejar / Permitir', past: 'Let', part: 'Let' },
    { en: 'Lie', es: 'Mentir / Yacer', past: 'Lay (Yacer) / Lied (Mentir)', part: 'Lain (Yacer) / Lied (Mentir)' },
    { en: 'Light', es: 'Encender', past: 'Lit', part: 'Lit' },
    { en: 'Lose', es: 'Perder', past: 'Lost', part: 'Lost' },
    { en: 'Make', es: 'Hacer / Fabricar', past: 'Made', part: 'Made' },
    { en: 'Mean', es: 'Significar', past: 'Meant', part: 'Meant' },
    { en: 'Meet', es: 'Conocer / Encontrarse', past: 'Met', part: 'Met' },
    { en: 'Overcome', es: 'Superar', past: 'Overcame', part: 'Overcome' },
    { en: 'Pay', es: 'Pagar', past: 'Paid', part: 'Paid' },
    { en: 'Put', es: 'Poner', past: 'Put', part: 'Put' },
    { en: 'Quit', es: 'Renunciar', past: 'Quit', part: 'Quit' },
    { en: 'Read', es: 'Leer', past: 'Read', part: 'Read' },
    { en: 'Ride', es: 'Montar', past: 'Rode', part: 'Ridden' },
    { en: 'Ring', es: 'Sonar / Llamar', past: 'Rang', part: 'Rung' },
    { en: 'Rise', es: 'Levantarse / Subir', past: 'Rose', part: 'Risen' },
    { en: 'Run', es: 'Correr', past: 'Ran', part: 'Run' },
    { en: 'Say', es: 'Decir', past: 'Said', part: 'Said' },
    { en: 'See', es: 'Ver', past: 'Saw', part: 'Seen' },
    { en: 'Seek', es: 'Buscar', past: 'Sought', part: 'Sought' },
    { en: 'Sell', es: 'Vender', past: 'Sold', part: 'Sold' },
    { en: 'Send', es: 'Enviar', past: 'Sent', part: 'Sent' },
    { en: 'Set', es: 'Establecer / Colocar', past: 'Set', part: 'Set' },
    { en: 'Sew', es: 'Coser', past: 'Sewed', part: 'Sewn/Sewed' },
    { en: 'Shake', es: 'Sacudir', past: 'Shook', part: 'Shaken' },
    { en: 'Shine', es: 'Brillar', past: 'Shone', part: 'Shone' },
    { en: 'Shoot', es: 'Disparar', past: 'Shot', part: 'Shot' },
    { en: 'Show', es: 'Mostrar', past: 'Showed', part: 'Shown' },
    { en: 'Shrink', es: 'Encoger', past: 'Shrank', part: 'Shrunk' },
    { en: 'Shut', es: 'Cerrar', past: 'Shut', part: 'Shut' },
    { en: 'Sing', es: 'Cantar', past: 'Sang', part: 'Sung' },
    { en: 'Sink', es: 'Hundirse', past: 'Sank', part: 'Sunk' }
];

const stringifyProps = (arr) => {
    return 'words: [\n            ' + arr.map(obj => `{ en: '${obj.en}', es: '${obj.es}', past: '${obj.past}', part: '${obj.part}' }`).join(',\n            ') + '\n        ]';
};

const regRepl = stringifyProps(regularVerbsNew);
const irrRepl = stringifyProps(irregularVerbsNew);

// Custom logic to replace instead of relying on regex which is flaky due to formatting differences
let startIndex = content.indexOf(`regularVerbs: {`);
let wordsIndex = content.indexOf(`words: [`, startIndex);
let endIndex = content.indexOf(`]`, wordsIndex) + 1;
content = content.substring(0, wordsIndex) + regRepl + content.substring(endIndex);

startIndex = content.indexOf(`irregularVerbs: {`);
wordsIndex = content.indexOf(`words: [`, startIndex);
endIndex = content.indexOf(`]`, wordsIndex) + 1;

content = content.substring(0, wordsIndex) + irrRepl + content.substring(endIndex);

fs.writeFileSync(vocabFile, content, 'utf8');
console.log('Done!');
