const fs = require('fs');

const vocabFile = 'src/data/vocabulary.js';
let content = fs.readFileSync(vocabFile, 'utf8');

const regularVerbsNew = [
    { en: 'Accept', es: 'Aceptar', past: 'Accepted', part: 'Accepted', esPast: 'Acepté', esPart: 'Aceptado' },
    { en: 'Add', es: 'Añadir / Sumar', past: 'Added', part: 'Added', esPast: 'Añadí', esPart: 'Añadido' },
    { en: 'Admire', es: 'Admirar', past: 'Admired', part: 'Admired', esPast: 'Admiré', esPart: 'Admirado' },
    { en: 'Admit', es: 'Admitir', past: 'Admitted', part: 'Admitted', esPast: 'Admití', esPart: 'Admitido' },
    { en: 'Advise', es: 'Aconsejar', past: 'Advised', part: 'Advised', esPast: 'Aconsejé', esPart: 'Aconsejado' },
    { en: 'Agree', es: 'Acordar / Estar de acuerdo', past: 'Agreed', part: 'Agreed', esPast: 'Acordé', esPart: 'Acordado' },
    { en: 'Allow', es: 'Permitir', past: 'Allowed', part: 'Allowed', esPast: 'Permití', esPart: 'Permitido' },
    { en: 'Announce', es: 'Anunciar', past: 'Announced', part: 'Announced', esPast: 'Anuncié', esPart: 'Anunciado' },
    { en: 'Answer', es: 'Responder', past: 'Answered', part: 'Answered', esPast: 'Respondí', esPart: 'Respondido' },
    { en: 'Apologize', es: 'Disculparse', past: 'Apologized', part: 'Apologized', esPast: 'Me disculpé', esPart: 'Disculpado' },
    { en: 'Appear', es: 'Aparecer', past: 'Appeared', part: 'Appeared', esPast: 'Aparecí', esPart: 'Aparecido' },
    { en: 'Appreciate', es: 'Apreciar', past: 'Appreciated', part: 'Appreciated', esPast: 'Aprecié', esPart: 'Apreciado' },
    { en: 'Approve', es: 'Aprobar', past: 'Approved', part: 'Approved', esPast: 'Aprobé', esPart: 'Aprobado' },
    { en: 'Argue', es: 'Discutir / Argumentar', past: 'Argued', part: 'Argued', esPast: 'Discutí', esPart: 'Discutido' },
    { en: 'Arrive', es: 'Llegar', past: 'Arrived', part: 'Arrived', esPast: 'Llegué', esPart: 'Llegado' },
    { en: 'Ask', es: 'Preguntar / Pedir', past: 'Asked', part: 'Asked', esPast: 'Pregunté', esPart: 'Preguntado' },
    { en: 'Assume', es: 'Asumir', past: 'Assumed', part: 'Assumed', esPast: 'Asumí', esPart: 'Asumido' },
    { en: 'Attach', es: 'Adjuntar', past: 'Attached', part: 'Attached', esPast: 'Adjunté', esPart: 'Adjuntado' },
    { en: 'Attack', es: 'Atacar', past: 'Attacked', part: 'Attacked', esPast: 'Ataqué', esPart: 'Atacado' },
    { en: 'Attempt', es: 'Intentar', past: 'Attempted', part: 'Attempted', esPast: 'Intenté', esPart: 'Intentado' },
    { en: 'Attend', es: 'Asistir', past: 'Attended', part: 'Attended', esPast: 'Asistí', esPart: 'Asistido' },
    { en: 'Attract', es: 'Atraer', past: 'Attracted', part: 'Attracted', esPast: 'Atraje', esPart: 'Atraído' },
    { en: 'Avoid', es: 'Evitar', past: 'Avoided', part: 'Avoided', esPast: 'Evité', esPart: 'Evitado' },
    { en: 'Bake', es: 'Hornear', past: 'Baked', part: 'Baked', esPast: 'Horneé', esPart: 'Horneado' },
    { en: 'Behave', es: 'Comportarse', past: 'Behaved', part: 'Behaved', esPast: 'Me comporté', esPart: 'Comportado' },
    { en: 'Belong', es: 'Pertenecer', past: 'Belonged', part: 'Belonged', esPast: 'Pertenecí', esPart: 'Pertenecido' },
    { en: 'Boil', es: 'Hervir', past: 'Boiled', part: 'Boiled', esPast: 'Herví', esPart: 'Hervido' },
    { en: 'Borrow', es: 'Pedir prestado', past: 'Borrowed', part: 'Borrowed', esPast: 'Pedí prestado', esPart: 'Pedido prestado' },
    { en: 'Bother', es: 'Molestar', past: 'Bothered', part: 'Bothered', esPast: 'Molesté', esPart: 'Molestado' },
    { en: 'Call', es: 'Llamar', past: 'Called', part: 'Called', esPast: 'Llamé', esPart: 'Llamado' },
    { en: 'Care', es: 'Importar / Cuidar', past: 'Cared', part: 'Cared', esPast: 'Cuidé', esPart: 'Cuidado' },
    { en: 'Carry', es: 'Llevar', past: 'Carried', part: 'Carried', esPast: 'Llevé', esPart: 'Llevado' },
    { en: 'Cause', es: 'Causar', past: 'Caused', part: 'Caused', esPast: 'Causé', esPart: 'Causado' },
    { en: 'Change', es: 'Cambiar', past: 'Changed', part: 'Changed', esPast: 'Cambié', esPart: 'Cambiado' },
    { en: 'Charge', es: 'Cargar / Cobrar', past: 'Charged', part: 'Charged', esPast: 'Cobré', esPart: 'Cobrado' },
    { en: 'Chase', es: 'Perseguir', past: 'Chased', part: 'Chased', esPast: 'Perseguí', esPart: 'Perseguido' },
    { en: 'Check', es: 'Comprobar / Revisar', past: 'Checked', part: 'Checked', esPast: 'Revisé', esPart: 'Revisado' },
    { en: 'Clean', es: 'Limpiar', past: 'Cleaned', part: 'Cleaned', esPast: 'Limpié', esPart: 'Limpiado' },
    { en: 'Clear', es: 'Aclarar / Despejar', past: 'Cleared', part: 'Cleared', esPast: 'Aclaré', esPart: 'Aclarado' },
    { en: 'Climb', es: 'Escalar', past: 'Climbed', part: 'Climbed', esPast: 'Escale', esPart: 'Escalado' },
    { en: 'Close', es: 'Cerrar', past: 'Closed', part: 'Closed', esPast: 'Cerré', esPart: 'Cerrado' },
    { en: 'Compare', es: 'Comparar', past: 'Compared', part: 'Compared', esPast: 'Comparé', esPart: 'Comparado' },
    { en: 'Complain', es: 'Quejarse', past: 'Complained', part: 'Complained', esPast: 'Me quejé', esPart: 'Quejado' },
    { en: 'Complete', es: 'Completar', past: 'Completed', part: 'Completed', esPast: 'Completé', esPart: 'Completado' },
    { en: 'Consider', es: 'Considerar', past: 'Considered', part: 'Considered', esPast: 'Consideré', esPart: 'Considerado' },
    { en: 'Continue', es: 'Continuar', past: 'Continued', part: 'Continued', esPast: 'Continué', esPart: 'Continuado' },
    { en: 'Cook', es: 'Cocinar', past: 'Cooked', part: 'Cooked', esPast: 'Cociné', esPart: 'Cocinado' },
    { en: 'Copy', es: 'Copiar', past: 'Copied', part: 'Copied', esPast: 'Copié', esPart: 'Copiado' },
    { en: 'Correct', es: 'Corregir', past: 'Corrected', part: 'Corrected', esPast: 'Corregí', esPart: 'Corregido' },
    { en: 'Count', es: 'Contar', past: 'Counted', part: 'Counted', esPast: 'Conté', esPart: 'Contado' },
    { en: 'Cover', es: 'Cubrir', past: 'Covered', part: 'Covered', esPast: 'Cubrí', esPart: 'Cubierto' },
    { en: 'Create', es: 'Crear', past: 'Created', part: 'Created', esPast: 'Creé', esPart: 'Creado' },
    { en: 'Cross', es: 'Cruzar', past: 'Crossed', part: 'Crossed', esPast: 'Crucé', esPart: 'Cruzado' },
    { en: 'Cry', es: 'Llorar', past: 'Cried', part: 'Cried', esPast: 'Lloré', esPart: 'Llorado' },
    { en: 'Dance', es: 'Bailar', past: 'Danced', part: 'Danced', esPast: 'Bailé', esPart: 'Bailado' },
    { en: 'Decide', es: 'Decidir', past: 'Decided', part: 'Decided', esPast: 'Decidí', esPart: 'Decidido' },
    { en: 'Deliver', es: 'Entregar', past: 'Delivered', part: 'Delivered', esPast: 'Entregué', esPart: 'Entregado' },
    { en: 'Depend', es: 'Depender', past: 'Depended', part: 'Depended', esPast: 'Dependí', esPart: 'Dependido' },
    { en: 'Describe', es: 'Describir', past: 'Described', part: 'Described', esPast: 'Describí', esPart: 'Descrito' },
    { en: 'Design', es: 'Diseñar', past: 'Designed', part: 'Designed', esPast: 'Diseñé', esPart: 'Diseñado' },
    { en: 'Destroy', es: 'Destruir', past: 'Destroyed', part: 'Destroyed', esPast: 'Destruí', esPart: 'Destruido' },
    { en: 'Develop', es: 'Desarrollar', past: 'Developed', part: 'Developed', esPast: 'Desarrollé', esPart: 'Desarrollado' },
    { en: 'Discover', es: 'Descubrir', past: 'Discovered', part: 'Discovered', esPast: 'Descubrí', esPart: 'Descubierto' },
    { en: 'Discuss', es: 'Discutir', past: 'Discussed', part: 'Discussed', esPast: 'Discutí', esPart: 'Discutido' },
    { en: 'Divide', es: 'Dividir', past: 'Divided', part: 'Divided', esPast: 'Dividí', esPart: 'Dividido' },
    { en: 'Dress', es: 'Vestir', past: 'Dressed', part: 'Dressed', esPast: 'Vestí', esPart: 'Vestido' },
    { en: 'Drop', es: 'Dejar caer', past: 'Dropped', part: 'Dropped', esPast: 'Dejé caer', esPart: 'Dejado caer' },
    { en: 'Earn', es: 'Ganar (dinero)', past: 'Earned', part: 'Earned', esPast: 'Gané', esPart: 'Ganado' },
    { en: 'Educate', es: 'Educar', past: 'Educated', part: 'Educated', esPast: 'Eduqué', esPart: 'Educado' },
    { en: 'Employ', es: 'Emplear', past: 'Employed', part: 'Employed', esPast: 'Empleé', esPart: 'Empleado' },
    { en: 'End', es: 'Terminar', past: 'Ended', part: 'Ended', esPast: 'Terminé', esPart: 'Terminado' },
    { en: 'Enjoy', es: 'Disfrutar', past: 'Enjoyed', part: 'Enjoyed', esPast: 'Disfruté', esPart: 'Disfrutado' },
    { en: 'Enter', es: 'Entrar', past: 'Entered', part: 'Entered', esPast: 'Entré', esPart: 'Entrado' },
    { en: 'Escape', es: 'Escapar', past: 'Escaped', part: 'Escaped', esPast: 'Escapé', esPart: 'Escapado' },
    { en: 'Examine', es: 'Examinar', past: 'Examined', part: 'Examined', esPast: 'Examiné', esPart: 'Examinado' },
    { en: 'Exist', es: 'Existir', past: 'Existed', part: 'Existed', esPast: 'Existí', esPart: 'Existido' },
    { en: 'Expect', es: 'Esperar (expectativa)', past: 'Expected', part: 'Expected', esPast: 'Esperé', esPart: 'Esperado' },
    { en: 'Explain', es: 'Explicar', past: 'Explained', part: 'Explained', esPast: 'Expliqué', esPart: 'Explicado' },
    { en: 'Face', es: 'Enfrentar', past: 'Faced', part: 'Faced', esPast: 'Enfrenté', esPart: 'Enfrentado' },
    { en: 'Fail', es: 'Fracasar / Suspender', past: 'Failed', part: 'Failed', esPast: 'Fracasé', esPart: 'Fracasado' },
    { en: 'Fill', es: 'Llenar', past: 'Filled', part: 'Filled', esPast: 'Llené', esPart: 'Llenado' },
    { en: 'Finish', es: 'Terminar', past: 'Finished', part: 'Finished', esPast: 'Terminé', esPart: 'Terminado' },
    { en: 'Fix', es: 'Arreglar', past: 'Fixed', part: 'Fixed', esPast: 'Arreglé', esPart: 'Arreglado' },
    { en: 'Follow', es: 'Seguir', past: 'Followed', part: 'Followed', esPast: 'Seguí', esPart: 'Seguido' },
    { en: 'Guess', es: 'Adivinar', past: 'Guessed', part: 'Guessed', esPast: 'Adiviné', esPart: 'Adivinado' },
    { en: 'Happen', es: 'Suceder', past: 'Happened', part: 'Happened', esPast: 'Sucedió', esPart: 'Sucedido' },
    { en: 'Hate', es: 'Odiar', past: 'Hated', part: 'Hated', esPast: 'Odié', esPart: 'Odiado' },
    { en: 'Help', es: 'Ayudar', past: 'Helped', part: 'Helped', esPast: 'Ayudé', esPart: 'Ayudado' },
    { en: 'Hope', es: 'Esperar (deseo)', past: 'Hoped', part: 'Hoped', esPast: 'Esperé', esPart: 'Esperado' },
    { en: 'Identify', es: 'Identificar', past: 'Identified', part: 'Identified', esPast: 'Identifiqué', esPart: 'Identificado' },
    { en: 'Imagine', es: 'Imaginar', past: 'Imagined', part: 'Imagined', esPast: 'Imaginé', esPart: 'Imaginado' },
    { en: 'Improve', es: 'Mejorar', past: 'Improved', part: 'Improved', esPast: 'Mejoré', esPart: 'Mejorado' },
    { en: 'Include', es: 'Incluir', past: 'Included', part: 'Included', esPast: 'Incluí', esPart: 'Incluido' },
    { en: 'Increase', es: 'Incrementar', past: 'Increased', part: 'Increased', esPast: 'Incrementé', esPart: 'Incrementado' },
    { en: 'Introduce', es: 'Introducir / Presentar', past: 'Introduced', part: 'Introduced', esPast: 'Presenté', esPart: 'Presentado' },
    { en: 'Invite', es: 'Invitar', past: 'Invited', part: 'Invited', esPast: 'Invité', esPart: 'Invitado' },
    { en: 'Join', es: 'Unirse', past: 'Joined', part: 'Joined', esPast: 'Me uní', esPart: 'Unido' },
    { en: 'Jump', es: 'Saltar', past: 'Jumped', part: 'Jumped', esPast: 'Salté', esPart: 'Saltado' },
    { en: 'Kill', es: 'Matar', past: 'Killed', part: 'Killed', esPast: 'Maté', esPart: 'Matado' },
    { en: 'Love', es: 'Amar', past: 'Loved', part: 'Loved', esPast: 'Amé', esPart: 'Amado' }
];

const irregularVerbsNew = [
    { en: 'Arise', es: 'Surgir', past: 'Arose', part: 'Arisen', esPast: 'Surgió', esPart: 'Surgido' },
    { en: 'Awake', es: 'Despertar', past: 'Awoke', part: 'Awoken', esPast: 'Desperté', esPart: 'Despertado' },
    { en: 'Be (am/is/are)', es: 'Ser / Estar', past: 'Was/Were', part: 'Been', esPast: 'Fui / Estuve', esPart: 'Sido / Estado' },
    { en: 'Bear', es: 'Soportar / Llevar', past: 'Bore', part: 'Borne/Born', esPast: 'Soporté', esPart: 'Soportado' },
    { en: 'Beat', es: 'Golpear / Vencer', past: 'Beat', part: 'Beaten', esPast: 'Golpeé', esPart: 'Golpeado' },
    { en: 'Become', es: 'Llegar a ser / Convertirse', past: 'Became', part: 'Become', esPast: 'Me convertí', esPart: 'Convertido' },
    { en: 'Begin', es: 'Empezar', past: 'Began', part: 'Begun', esPast: 'Empecé', esPart: 'Empezado' },
    { en: 'Bend', es: 'Doblar', past: 'Bent', part: 'Bent', esPast: 'Doblé', esPart: 'Doblado' },
    { en: 'Bet', es: 'Apostar', past: 'Bet', part: 'Bet', esPast: 'Aposté', esPart: 'Apostado' },
    { en: 'Bind', es: 'Atar', past: 'Bound', part: 'Bound', esPast: 'Até', esPart: 'Atado' },
    { en: 'Bite', es: 'Morder', past: 'Bit', part: 'Bitten', esPast: 'Mordí', esPart: 'Mordido' },
    { en: 'Bleed', es: 'Sangrar', past: 'Bled', part: 'Bled', esPast: 'Sangré', esPart: 'Sangrado' },
    { en: 'Blow', es: 'Soplar', past: 'Blew', part: 'Blown', esPast: 'Soplé', esPart: 'Soplado' },
    { en: 'Break', es: 'Romper', past: 'Broke', part: 'Broken', esPast: 'Rompí', esPart: 'Roto' },
    { en: 'Bring', es: 'Traer', past: 'Brought', part: 'Brought', esPast: 'Traje', esPart: 'Traído' },
    { en: 'Build', es: 'Construir', past: 'Built', part: 'Built', esPast: 'Construí', esPart: 'Construido' },
    { en: 'Burn', es: 'Quemar', past: 'Burnt/Burned', part: 'Burnt/Burned', esPast: 'Quemé', esPart: 'Quemado' },
    { en: 'Burst', es: 'Estallar', past: 'Burst', part: 'Burst', esPast: 'Estallé', esPart: 'Estallado' },
    { en: 'Buy', es: 'Comprar', past: 'Bought', part: 'Bought', esPast: 'Compré', esPart: 'Comprado' },
    { en: 'Cast', es: 'Lanzar / Repartir', past: 'Cast', part: 'Cast', esPast: 'Lancé', esPart: 'Lanzado' },
    { en: 'Catch', es: 'Atrapar', past: 'Caught', part: 'Caught', esPast: 'Atrapé', esPart: 'Atrapado' },
    { en: 'Choose', es: 'Elegir', past: 'Chose', part: 'Chosen', esPast: 'Elegí', esPart: 'Elegido' },
    { en: 'Cling', es: 'Aferrarse', past: 'Clung', part: 'Clung', esPast: 'Me aferré', esPart: 'Aferrado' },
    { en: 'Come', es: 'Venir', past: 'Came', part: 'Come', esPast: 'Vine', esPart: 'Venido' },
    { en: 'Cost', es: 'Costar', past: 'Cost', part: 'Cost', esPast: 'Costó', esPart: 'Costado' },
    { en: 'Creep', es: 'Arrastrarse', past: 'Crept', part: 'Crept', esPast: 'Me arrastré', esPart: 'Arrastrado' },
    { en: 'Cut', es: 'Cortar', past: 'Cut', part: 'Cut', esPast: 'Corté', esPart: 'Cortado' },
    { en: 'Deal', es: 'Tratar / Negociar', past: 'Dealt', part: 'Dealt', esPast: 'Traté', esPart: 'Tratado' },
    { en: 'Dig', es: 'Cavar', past: 'Dug', part: 'Dug', esPast: 'Cavé', esPart: 'Cavado' },
    { en: 'Do / Does', es: 'Hacer', past: 'Did', part: 'Done', esPast: 'Hice', esPart: 'Hecho' },
    { en: 'Draw', es: 'Dibujar', past: 'Drew', part: 'Drawn', esPast: 'Dibujé', esPart: 'Dibujado' },
    { en: 'Dream', es: 'Soñar', past: 'Dreamt/Dreamed', part: 'Dreamt/Dreamed', esPast: 'Soñé', esPart: 'Soñado' },
    { en: 'Drink', es: 'Beber', past: 'Drank', part: 'Drunk', esPast: 'Bebí', esPart: 'Bebido' },
    { en: 'Drive', es: 'Conducir', past: 'Drove', part: 'Driven', esPast: 'Conduje', esPart: 'Conducido' },
    { en: 'Eat', es: 'Comer', past: 'Ate', part: 'Eaten', esPast: 'Comí', esPart: 'Comido' },
    { en: 'Fall', es: 'Caer', past: 'Fell', part: 'Fallen', esPast: 'Caí', esPart: 'Caído' },
    { en: 'Feed', es: 'Alimentar', past: 'Fed', part: 'Fed', esPast: 'Alimenté', esPart: 'Alimentado' },
    { en: 'Feel', es: 'Sentir', past: 'Felt', part: 'Felt', esPast: 'Sentí', esPart: 'Sentido' },
    { en: 'Fight', es: 'Pelear', past: 'Fought', part: 'Fought', esPast: 'Peleé', esPart: 'Peleado' },
    { en: 'Find', es: 'Encontrar', past: 'Found', part: 'Found', esPast: 'Encontré', esPart: 'Encontrado' },
    { en: 'Flee', es: 'Huir', past: 'Fled', part: 'Fled', esPast: 'Huí', esPart: 'Huido' },
    { en: 'Fling', es: 'Arrojar', past: 'Flung', part: 'Flung', esPast: 'Arrojé', esPart: 'Arrojado' },
    { en: 'Fly', es: 'Volar', past: 'Flew', part: 'Flown', esPast: 'Volé', esPart: 'Volado' },
    { en: 'Forbid', es: 'Prohibir', past: 'Forbade', part: 'Forbidden', esPast: 'Prohibí', esPart: 'Prohibido' },
    { en: 'Forget', es: 'Olvidar', past: 'Forgot', part: 'Forgotten', esPast: 'Olvidé', esPart: 'Olvidado' },
    { en: 'Forgive', es: 'Perdonar', past: 'Forgave', part: 'Forgiven', esPast: 'Perdoné', esPart: 'Perdonado' },
    { en: 'Freeze', es: 'Congelar', past: 'Froze', part: 'Frozen', esPast: 'Congelé', esPart: 'Congelado' },
    { en: 'Get', es: 'Obtener / Conseguir', past: 'Got', part: 'Got/Gotten', esPast: 'Obtuve', esPart: 'Obtenido' },
    { en: 'Give', es: 'Dar', past: 'Gave', part: 'Given', esPast: 'Di', esPart: 'Dado' },
    { en: 'Go', es: 'Ir', past: 'Went', part: 'Gone', esPast: 'Fui', esPart: 'Ido' },
    { en: 'Grind', es: 'Moler', past: 'Ground', part: 'Ground', esPast: 'Molí', esPart: 'Molido' },
    { en: 'Grow', es: 'Crecer / Cultivar', past: 'Grew', part: 'Grown', esPast: 'Crecí', esPart: 'Crecido' },
    { en: 'Hang', es: 'Colgar', past: 'Hung', part: 'Hung', esPast: 'Colgué', esPart: 'Colgado' },
    { en: 'Have / Has', es: 'Tener / Haber', past: 'Had', part: 'Had', esPast: 'Tuve', esPart: 'Tenido' },
    { en: 'Hear', es: 'Oír', past: 'Heard', part: 'Heard', esPast: 'Oí', esPart: 'Oído' },
    { en: 'Hide', es: 'Esconder', past: 'Hid', part: 'Hidden', esPast: 'Escondí', esPart: 'Escondido' },
    { en: 'Hit', es: 'Golpear', past: 'Hit', part: 'Hit', esPast: 'Golpeé', esPart: 'Golpeado' },
    { en: 'Hold', es: 'Sostener', past: 'Held', part: 'Held', esPast: 'Sostuve', esPart: 'Sostenido' },
    { en: 'Hurt', es: 'Herir / Doler', past: 'Hurt', part: 'Hurt', esPast: 'Herí', esPart: 'Herido' },
    { en: 'Keep', es: 'Mantener / Guardar', past: 'Kept', part: 'Kept', esPast: 'Mantuve', esPart: 'Mantenido' },
    { en: 'Kneel', es: 'Arrodillarse', past: 'Knelt', part: 'Knelt', esPast: 'Me arrodillé', esPart: 'Arrodillado' },
    { en: 'Know', es: 'Saber / Conocer', past: 'Knew', part: 'Known', esPast: 'Supe', esPart: 'Sabido' },
    { en: 'Lay', es: 'Poner (algo)', past: 'Laid', part: 'Laid', esPast: 'Puse', esPart: 'Puesto' },
    { en: 'Lead', es: 'Liderar / Guiar', past: 'Led', part: 'Led', esPast: 'Lideré', esPart: 'Liderado' },
    { en: 'Lean', es: 'Apoyarse', past: 'Leant/Leaned', part: 'Leant/Leaned', esPast: 'Me apoyé', esPart: 'Apoyado' },
    { en: 'Leap', es: 'Saltar', past: 'Leapt/Leaped', part: 'Leapt/Leaped', esPast: 'Salté', esPart: 'Saltado' },
    { en: 'Learn', es: 'Aprender', past: 'Learnt/Learned', part: 'Learnt/Learned', esPast: 'Aprendí', esPart: 'Aprendido' },
    { en: 'Leave', es: 'Dejar / Salir', past: 'Left', part: 'Left', esPast: 'Dejé', esPart: 'Dejado' },
    { en: 'Lend', es: 'Prestar', past: 'Lent', part: 'Lent', esPast: 'Presté', esPart: 'Prestado' },
    { en: 'Let', es: 'Dejar / Permitir', past: 'Let', part: 'Let', esPast: 'Dejé', esPart: 'Dejado' },
    { en: 'Lie', es: 'Mentir / Yacer', past: 'Lay (Yacer) / Lied (Mentir)', part: 'Lain (Yacer) / Lied (Mentir)', esPast: 'Yací / Mentí', esPart: 'Yacido / Mentido' },
    { en: 'Light', es: 'Encender', past: 'Lit', part: 'Lit', esPast: 'Encendí', esPart: 'Encendido' },
    { en: 'Lose', es: 'Perder', past: 'Lost', part: 'Lost', esPast: 'Perdí', esPart: 'Perdido' },
    { en: 'Make', es: 'Hacer / Fabricar', past: 'Made', part: 'Made', esPast: 'Hice', esPart: 'Hecho' },
    { en: 'Mean', es: 'Significar', past: 'Meant', part: 'Meant', esPast: 'Significó', esPart: 'Significado' },
    { en: 'Meet', es: 'Conocer / Encontrarse', past: 'Met', part: 'Met', esPast: 'Conocí', esPart: 'Conocido' },
    { en: 'Overcome', es: 'Superar', past: 'Overcame', part: 'Overcome', esPast: 'Superé', esPart: 'Superado' },
    { en: 'Pay', es: 'Pagar', past: 'Paid', part: 'Paid', esPast: 'Pagué', esPart: 'Pagado' },
    { en: 'Put', es: 'Poner', past: 'Put', part: 'Put', esPast: 'Puse', esPart: 'Puesto' },
    { en: 'Quit', es: 'Renunciar', past: 'Quit', part: 'Quit', esPast: 'Renuncié', esPart: 'Renunciado' },
    { en: 'Read', es: 'Leer', past: 'Read', part: 'Read', esPast: 'Leí', esPart: 'Leído' },
    { en: 'Ride', es: 'Montar', past: 'Rode', part: 'Ridden', esPast: 'Monté', esPart: 'Montado' },
    { en: 'Ring', es: 'Sonar / Llamar', past: 'Rang', part: 'Rung', esPast: 'Sonó', esPart: 'Sonado' },
    { en: 'Rise', es: 'Levantarse / Subir', past: 'Rose', part: 'Risen', esPast: 'Me levanté', esPart: 'Levantado' },
    { en: 'Run', es: 'Correr', past: 'Ran', part: 'Run', esPast: 'Corrí', esPart: 'Corrido' },
    { en: 'Say', es: 'Decir', past: 'Said', part: 'Said', esPast: 'Dije', esPart: 'Dicho' },
    { en: 'See', es: 'Ver', past: 'Saw', part: 'Seen', esPast: 'Vi', esPart: 'Visto' },
    { en: 'Seek', es: 'Buscar', past: 'Sought', part: 'Sought', esPast: 'Busqué', esPart: 'Buscado' },
    { en: 'Sell', es: 'Vender', past: 'Sold', part: 'Sold', esPast: 'Vendí', esPart: 'Vendido' },
    { en: 'Send', es: 'Enviar', past: 'Sent', part: 'Sent', esPast: 'Envié', esPart: 'Enviado' },
    { en: 'Set', es: 'Establecer / Colocar', past: 'Set', part: 'Set', esPast: 'Establecí', esPart: 'Establecido' },
    { en: 'Sew', es: 'Coser', past: 'Sewed', part: 'Sewn/Sewed', esPast: 'Cosí', esPart: 'Cosido' },
    { en: 'Shake', es: 'Sacudir', past: 'Shook', part: 'Shaken', esPast: 'Sacudí', esPart: 'Sacudido' },
    { en: 'Shine', es: 'Brillar', past: 'Shone', part: 'Shone', esPast: 'Brilló', esPart: 'Brillado' },
    { en: 'Shoot', es: 'Disparar', past: 'Shot', part: 'Shot', esPast: 'Disparé', esPart: 'Disparado' },
    { en: 'Show', es: 'Mostrar', past: 'Showed', part: 'Shown', esPast: 'Mostré', esPart: 'Mostrado' },
    { en: 'Shrink', es: 'Encoger', past: 'Shrank', part: 'Shrunk', esPast: 'Encogí', esPart: 'Encogido' },
    { en: 'Shut', es: 'Cerrar', past: 'Shut', part: 'Shut', esPast: 'Cerré', esPart: 'Cerrado' },
    { en: 'Sing', es: 'Cantar', past: 'Sang', part: 'Sung', esPast: 'Canté', esPart: 'Cantado' },
    { en: 'Sink', es: 'Hundirse', past: 'Sank', part: 'Sunk', esPast: 'Me hundí', esPart: 'Hundido' }
];

const stringifyProps = (arr) => {
    return 'words: [\n            ' + arr.map(obj => `{ en: '${obj.en}', es: '${obj.es}', past: '${obj.past}', part: '${obj.part}', esPast: '${obj.esPast}', esPart: '${obj.esPart}' }`).join(',\n            ') + '\n        ]';
};

const regRepl = stringifyProps(regularVerbsNew);
const irrRepl = stringifyProps(irregularVerbsNew);

let startIndex = content.indexOf(`regularVerbs: {`);
let wordsIndex = content.indexOf(`words: [`, startIndex);
let endIndex = content.indexOf(`]`, wordsIndex) + 1;
content = content.substring(0, wordsIndex) + regRepl + content.substring(endIndex);

startIndex = content.indexOf(`irregularVerbs: {`);
wordsIndex = content.indexOf(`words: [`, startIndex);
endIndex = content.indexOf(`]`, wordsIndex) + 1;
content = content.substring(0, wordsIndex) + irrRepl + content.substring(endIndex);

fs.writeFileSync(vocabFile, content, 'utf8');
console.log('Translations updated!');
