const Database = require('better-sqlite3');
const path = require('path');
const dbPath = path.join(__dirname, 'data', 'database.db');
const db = new Database(dbPath);
const users = db.prepare('SELECT id, username, email FROM users').all();
console.log('--- USERS ---');
console.log(JSON.stringify(users, null, 2));
const topics = db.prepare('SELECT id, level, number FROM topics LIMIT 5').all();
console.log('--- TOPICS ---');
console.log(JSON.stringify(topics, null, 2));
